---
title: "Asthma_poverty"
author: "Qi Shao"
date: "12/3/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plyr)
library(readr)
library(readxl)
```


```{r}
children1 = read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Asthma Hospitalizations (Children 0 to 4 Yrs Old)") %>%
  filter(Measure == "Rate") %>%
  select(name,geo_entity_name,year_description,data_value) 
  
ggplot(children1, aes(x = year_description, y = data_value)) + 
  geom_boxplot()+
  labs(
    title = "year vs asthma Children 0 to 4  Yrs Old ",
    x = "year",
    y = "asthma"
  )


children2 = read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Asthma Hospitalizations (Children 5 to 14 Yrs Old)") %>%
  filter(Measure == "Rate") %>%
  select(name,geo_entity_name,year_description,data_value) 
  
ggplot(children2, aes(x = year_description, y = data_value)) + 
  geom_boxplot()+
  labs(
    title = "year vs asthma Children 5 to 14 Yrs Old ",
    x = "year",
    y = "asthma"
  )


asthma_air = read_csv("./data/asthma_air/Data.csv") %>%
  filter(str_detect(year_description, "^20|^An")) %>%
  mutate(year_description = str_remove(year_description, "Annual Average ")) %>%
    filter(year_description == 2015)

sulfur_dioxide= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Sulfur Dioxide (SO2)") %>%
  filter(year_description == "Winter 2014-15")

ozone= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Ozone (O3)") %>%
  filter(year_description == "Summer 2015")

poverty= read_csv("./data/poverty/Data.csv") %>%
  filter(year_description == "2011-15" )

smoke = read_csv("./data/smoking_exer/Data.csv") %>%
  filter(year_description == "2015" )

data = rbind(asthma_air,sulfur_dioxide,ozone, poverty, smoke)
  


asthma_air1 = data %>%
  select(name, description, Measure, geo_entity_name, geo_entity_id, year = year_description, data_value) %>%
  janitor::clean_names() %>% 
  filter(measure %in% c("Mean", "Rate", "Number", "Percent", "Age-Adjusted Percent", "Age-Adjusted Rate ")) %>%
  mutate(name_measure=str_c(name,"-",measure)) %>%
  select(-name, -measure, -description, -year) %>%
  spread(key = name_measure, value = data_value) %>% 
    janitor::clean_names() %>%
  mutate(ln_asthma = log(asthma_hospitalizations_children_0_to_4_yrs_old_rate))%>%
  janitor::clean_names() 






```


##poverty vs asthma

```{r}

ggplot(data = asthma_air1) +
  geom_point(aes(x = poverty_number, y = asthma_emergency_department_visits_children_5_to_14_yrs_old_rate, color = "red"))+
  geom_point(aes(x = poverty_number, y = asthma_emergency_department_visits_children_0_to_4_yrs_old_rate, color = "blue"))+
  geom_smooth(aes(x = poverty_number, y = asthma_emergency_department_visits_children_5_to_14_yrs_old_rate, color = "red"),se = FALSE, method = "lm")+
  geom_smooth(aes(x = poverty_number, y = asthma_emergency_department_visits_children_0_to_4_yrs_old_rate, color = "blue"),se = FALSE, method = "lm")

asthma_poverty = lm(asthma_emergency_department_visits_children_5_to_14_yrs_old_rate ~ poverty_number, data = asthma_air1)

summary(asthma_poverty)
```


tidy tree data
```{r}
tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  janitor::clean_names() %>%
  filter(status == "Alive", health == "Good") 

tree_df %>%
  group_by(boroname) %>%
  dplyr::summarise(total = n()) 

zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   select(-zipcode_no, -uhf42_code) %>%
   filter(is.na(zipcode) == FALSE)

mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")
area = mydat$SHAPE_Area

tree_total_uhf42 = left_join(tree_df, zipcode_uhf42, by = "zipcode") %>%
  group_by(uhf42_name) %>%
  dplyr::summarize(total = n()) %>%
  mutate(area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  mutate(tree_density = total/area, 
         uhf42_name = forcats::fct_reorder(uhf42_name, tree_density)) %>%
  select(geo_entity_name = uhf42_name, tree_density)


asthma_tree = left_join(tree_total_uhf42, asthma_air1)

names(asthma_tree)

```

## Tree density vs air polution
```{r}

 ggplot(data = asthma_tree) +
  geom_point(aes(x = tree_density, y = asthma_emergency_department_visits_children_5_to_14_yrs_old_rate, color = "red"))+
  geom_point(aes(x = tree_density, y = asthma_emergency_department_visits_children_0_to_4_yrs_old_rate, color = "blue"))+
  geom_smooth(aes(x = tree_density, y = asthma_emergency_department_visits_children_5_to_14_yrs_old_rate, color = "red"),se = FALSE, method = "lm")+
  geom_smooth(aes(x = tree_density, y = asthma_emergency_department_visits_children_0_to_4_yrs_old_rate, color = "blue"),se = FALSE, method = "lm")


 ggplot(data = asthma_tree) +
  geom_point(aes(x = tree_density, y = sulfur_dioxide_so2_mean))+
  geom_smooth(aes(x = tree_density, y = sulfur_dioxide_so2_mean),se = FALSE, method = "lm")
 

 tree_poverty = lm(tree_density ~ poverty_number, data = asthma_tree)
 
 summary(tree_poverty)
 
  tree_asthma = lm(asthma_emergency_department_visits_children_0_to_4_yrs_old_rate ~ tree_density, data = asthma_tree)
 
 summary(tree_asthma)
 
 
 
multi_1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate ~ poverty_number + tree_density + sulfur_dioxide_so2_mean, data = asthma_tree)


multi_1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate ~ tree_density + sulfur_dioxide_so2_mean, data = asthma_tree)


 
 

```