---
title: "plot"
author: "Xinyao Wu"
date: "2018/11/19"
output: html_document
---

```{r plot setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
library(patchwork)
```
#Data
```{r}
asthma = read.csv("./data/asthma_air/Data.csv")
asthma %>% 
distinct(name) %>% pull()
```
##From "tidy_asthma&air.rmd"
```{r including = FALSE}
 
asthma_air = read_csv("./data/asthma_air/Data.csv") %>%
  filter(str_detect(year_description, "^20|^An")) %>%
  mutate(year_description = str_remove(year_description, "Annual Average ")) %>%
    filter(year_description == 2015)

sulfur_dioxide= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Sulfur Dioxide (SO2)") %>%
  filter(year_description == "Winter 2014-15")

ozone= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Ozone (O3)") %>%
  filter(year_description == "Summer 2015")

poverty= read_csv("./data/poverty/Data.csv") %>%
  filter(year_description == "2011-15" )

smoke = read_csv("./data/smoking_exer/Data.csv") %>%
  filter(year_description == "2015" )

data = rbind(asthma_air,sulfur_dioxide,ozone, poverty, smoke)
  
asthma_air1 = data %>%
  select(name, description, Measure, geo_entity_name, geo_entity_id, year = year_description, data_value) %>%
  janitor::clean_names() %>% 
  filter(measure %in% c("Mean", "Rate", "Number", "Percent", "Age-Adjusted Percent", "Age-Adjusted Rate ")) %>%
  mutate(name_measure=str_c(name,"-",measure)) %>%
  select(-name, -measure, -description, -year) %>%
  spread(key = name_measure, value = data_value) 


```

### An alternative plot/ now not related 
```{r}
asthma %>% 
  filter(geo_type_name=="UHF42") %>% 
  filter(measurement_type_id == "1") %>% #precent#
  filter(name == "Asthma Hospitalizations (Children 0 to 4 Yrs Old)"|name =="Asthma Hospitalizations (Children 5 to 14 Yrs Old)") %>%
  #choose 5 geo_entity_name
  #filter(geo_entity_name=="Rockaways"|geo_entity_name == "Port Richmond") %>% 
  mutate(
    loco = as.numeric(geo_entity_name)
  ) %>% 
  ggplot(aes(x = loco, y = data_value,color = name))+geom_point(alpha = 0.3)+geom_smooth(se = FALSE)+
  theme(axis.text.x = element_text(angle = 90,size = 3.5))+ theme(legend.position = "bottom")+
  facet_grid(~year_description)
```

### asthma vs air_pollution

##### NO vs.astma
```{r}
 asthma_air1 = asthma_air1 %>% 
  janitor::clean_names()
  NO = ggplot(asthma_air1)+
  geom_point(aes(x = nitric_oxide_no_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_smooth(aes(x = nitric_oxide_no_mean, y = asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"),se =FALSE) +
  geom_point(aes(x = nitric_oxide_no_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"))+
  geom_smooth(aes(x = nitric_oxide_no_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"),se =FALSE)  +
  theme(legend.position ="bottom")
```


#### O3 vs. asthma
```{r}
O3= asthma_air1 %>% 
  ggplot()+
  geom_point(aes(x = ozone_o3_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_smooth(aes(x = ozone_o3_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"),method = lm,se = FALSE)+
  geom_point(aes(x = ozone_o3_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_4_to_14_yrs_old"))+
  geom_smooth(aes(x = ozone_o3_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_4_to_14_yrs_old"),method = lm,se =FALSE) +
  theme(legend.position ="bottom")

```

##### NO2 vs.astma
```{r}
 NO2 = ggplot(asthma_air1)+
  geom_point(aes(x = nitrogen_dioxide_no2_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_smooth(aes(x = nitrogen_dioxide_no2_mean, y = asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"),method = lm,se =FALSE) +
  geom_point(aes(x = nitrogen_dioxide_no2_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"))+
  geom_smooth(aes(x = nitrogen_dioxide_no2_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"),method = lm,se =FALSE) +
  theme(legend.position ="bottom")
```


##### SO2 vs.astma
```{r}

 SO2 =  ggplot(asthma_air1)+
  geom_point(aes(x = sulfur_dioxide_so2_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_smooth(aes(x = sulfur_dioxide_so2_mean, y = asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"),method = lm,se =FALSE) +
  geom_point(aes(x = sulfur_dioxide_so2_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"))+
  geom_smooth(aes(x = sulfur_dioxide_so2_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"),method = lm,se =FALSE) +
  theme(legend.position ="bottom")
```


##### pm2.5 vs.astma
```{r}
  pm2.5 = ggplot(asthma_air1)+
  geom_point(aes(x = fine_particulate_matter_pm2_5_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_smooth(aes(x = fine_particulate_matter_pm2_5_mean, y = asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"),method = lm,se =FALSE) +
  geom_point(aes(x = fine_particulate_matter_pm2_5_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"))+
  geom_smooth(aes(x = fine_particulate_matter_pm2_5_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"),method = lm,se =FALSE) +
  theme(legend.position ="bottom")
```

##### black_carbon_mean
```{r}

  black_carbon =ggplot(asthma_air1)+
  geom_point(aes(x = black_carbon_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_smooth(aes(x = black_carbon_mean, y = asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"),method = lm,se =FALSE) +
  geom_point(aes(x = black_carbon_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"))+
  geom_smooth(aes(x = black_carbon_mean, y = asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"),method = lm,se =FALSE)+
  theme(legend.position ="bottom")
```


```{r}

NO+NO2+O3

black_carbon+pm2.5+SO2

```

##TRY line_plot(NO asthma)

```{r}
asthma_air1 = asthma_air1 %>% 
  janitor::clean_names()
  ggplot(asthma_air1)+
  geom_line(aes(x = nitric_oxide_no_mean, y =asthma_hospitalizations_children_0_to_4_yrs_old_rate,color = "children_0_to_4_yrs_old"))+
  geom_line(aes(x = nitric_oxide_no_mean, y=asthma_hospitalizations_children_5_to_14_yrs_old_rate,color = "children_5_to_14_yrs_old"))
```


### year vs. asthma (by boro) 
```{r}
asthma %>% 
  filter(geo_type_name=="UHF42") %>% 
  filter(measurement_type_id == "1") %>% #precent#
  filter(name == "Asthma Hospitalizations (Children 0 to 4 Yrs Old)"|name =="Asthma Hospitalizations (Children 5 to 14 Yrs Old)") %>%
  #choose 5 geo_entity_name
  #filter(geo_entity_name=="Rockaways"|geo_entity_name == "Port Richmond") %>% 
  mutate(
    loco = as.numeric(geo_entity_name)
  ) %>% 
  ggplot(aes(x = loco, y = data_value,color = name))+geom_point(alpha = 0.3)+geom_smooth(se = FALSE)+
  theme(axis.text.x = element_text(angle = 90,size = 3.5))+ theme(legend.position = "bottom")


```

#Linear Regression

### p.value of 5_to_14_yrs old children 
```{r}
so2_child_reg = lm(asthma_hospitalizations_children_5_to_14_yrs_old_rate~sulfur_dioxide_so2_mean,data = asthma_air1) %>% broom::tidy()
###pm2.5
pm2.5_child_reg = lm(asthma_hospitalizations_children_5_to_14_yrs_old_rate~fine_particulate_matter_pm2_5_mean,data = asthma_air1)%>% broom::tidy()
###no
no_child_reg = lm(asthma_hospitalizations_children_5_to_14_yrs_old_rate~nitric_oxide_no_mean,data = asthma_air1)%>% broom::tidy()
###no2
no2_child_reg = lm(asthma_hospitalizations_children_5_to_14_yrs_old_rate~nitrogen_dioxide_no2_mean,data = asthma_air1)%>% broom::tidy()
###o3
o3_child_reg = lm(asthma_hospitalizations_children_5_to_14_yrs_old_rate~ozone_o3_mean,data = asthma_air1)%>% broom::tidy()

bind_rows(so2_child_reg,pm2.5_child_reg,no_child_reg,no2_child_reg,o3_child_reg) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(
    term = str_replace(term,"_mean","")
  ) %>% 
  select(term,p.value) %>% 
  knitr::kable(caption = "p.value of different air pollutants in  linear modeling asthma hospitalizations rate children (5_to_14_yrs old)")
  
```

### p.value of 5_to_14_yrs old children 
```{r}
so2_child_reg1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate~sulfur_dioxide_so2_mean,data = asthma_air1) %>% broom::tidy()
###pm2.5
pm2.5_child_reg1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate~fine_particulate_matter_pm2_5_mean,data = asthma_air1)%>% broom::tidy()
###no
no_child_reg1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate~nitric_oxide_no_mean,data = asthma_air1)%>% broom::tidy()
###no2
no2_child_reg1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate~nitrogen_dioxide_no2_mean,data = asthma_air1)%>% broom::tidy()
###o3
o3_child_reg1 = lm(asthma_hospitalizations_children_0_to_4_yrs_old_rate~ozone_o3_mean,data = asthma_air1)%>% broom::tidy()

bind_rows(so2_child_reg1,pm2.5_child_reg1,no_child_reg1,no2_child_reg1,o3_child_reg1) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(
    term = str_replace(term,"_mean","")
  ) %>% 
  dplyr::select(term,p.value) %>% 
  knitr::kable(caption = "p.value of different air pollutants in  linear modeling asthma hospitalizations rate children (0_to_4_yrs old)")
  
```




###so2
```{r}
so2_child_reg2 = lm(asthma_emergency_department_visits_children_5_to_14_yrs_old_rate~sulfur_dioxide_so2_mean,data = asthma_air1) %>% broom::tidy()
```

###pm2.5
```{r}
pm2.5_child_reg2 = lm(asthma_emergency_department_visits_children_5_to_14_yrs_old_rate~fine_particulate_matter_pm2_5_mean,data = asthma_air1)
summary(pm2.5_child_reg2)
```

###no
```{r}
no_child_reg2 = lm(asthma_emergency_department_visits_children_5_to_14_yrs_old_rate~nitric_oxide_no_mean,data = asthma_air1)
summary(no_child_reg2)
```
###no2
```{r}
no2_child_reg2 = lm(asthma_emergency_department_visits_children_5_to_14_yrs_old_rate~nitrogen_dioxide_no2_mean,data = asthma_air1)
summary(no2_child_reg2)
```

###o3
```{r}
o3_child_reg2 = lm(asthma_emergency_department_visits_children_5_to_14_yrs_old_rate~ozone_o3_mean,data = asthma_air1)
summary(o3_child_reg2)
```



#asthma distrubution
```{r}
asthma_air1 %>% 
  gather(key = "group",value = value,asthma_hospitalizations_children_5_to_14_yrs_old_rate,asthma_hospitalizations_children_0_to_4_yrs_old_rate) %>% 
  filter(geo_entity_id<=310&geo_entity_id>=301) %>% 
  ggplot(aes(x = reorder(geo_entity_name,asthma_emergency_department_visits_children_5_to_14_yrs_old_rate),y = value, color =group))+geom_point()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45,size = 4.5)
                                                                              )
```


```{r}
asthma_air1 %>% 
  gather(key = "group",value = value,asthma_hospitalizations_children_5_to_14_yrs_old_rate,asthma_hospitalizations_children_0_to_4_yrs_old_rate) %>% 
  ggplot(aes(x = reorder(geo_entity_name,asthma_emergency_department_visits_children_5_to_14_yrs_old_rate),y = value, color =group))+geom_point()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45,size = 4.5))
```


```{r}

as1= asthma_air1 %>% 
  gather(key = "group",value = value,asthma_hospitalizations_children_5_to_14_yrs_old_rate,asthma_hospitalizations_children_0_to_4_yrs_old_rate) %>% 
  ggplot(aes(x = reorder(geo_entity_name,asthma_emergency_department_visits_children_5_to_14_yrs_old_rate),y = value, color =group))+geom_point()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45,size = 4.5),
         axis.title = element_text(size = 4.5))

```

```{r}
 pov =  asthma_air1 %>%
  janitor::clean_names() %>% 
 ggplot(aes(x = reorder(geo_entity_name,asthma_emergency_department_visits_children_5_to_14_yrs_old_rate),y = poverty_percent))+geom_point()+
  theme(legend.position = "bottom",axis.text.x = element_text(angle = 45,size = 4.5),
        axis.title = element_text(size = 4.5))

as1
pov

```

















