---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: cosmo
---

```{r dashboard, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(rvest)
library(httr)
library(plotly)
library(rgdal)
library(patchwork)
library(readr)
library(ggplot2)
library(readxl)
theme_set(theme_bw())
```

```{r tidy,include= FALSE}
## Tidy tree data
tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  janitor::clean_names() %>%
  filter(status == "Alive") 

zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = "zipcode") 

## Tidy map data
mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")
area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_code) == FALSE)

tree_df = left_join(tree_df, area, by = "uhf42_code")

tree_density = tree_df %>%
  group_by(uhf42_name, uhf42_code, area) %>%
  dplyr::summarize(tree_total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  group_by(uhf42_name) %>%
  dplyr::mutate(tree_density = tree_total/area) %>%
  ungroup() %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))

## Tidy map data
map_data = fortify(mydat) %>%
  dplyr::select(id, everything() )%>%
  nest(long:group)
map_data$uhf = mydat$UHFCODE
map_data = map_data %>%
  unnest %>%
  dplyr::select(-id) %>%
  dplyr::select(id = uhf, everything()) %>%
  dplyr::select(long, lat, everything())
names(map_data)[1:2] = c("x","y") 

## Tidy asthma data
asthma_air_poverty = read_csv("./data/asthma_pollutes_poverty.csv") %>%
  select(geo_entity_id, geo_entity_name, name, data_value) %>%
  filter(is.na(geo_entity_id) == FALSE) %>%
  spread(key = name, value = data_value) %>%
  janitor::clean_names() %>%
  select(poverty, children_under_5_years_old_in_poverty, everything()) %>%
  mutate(asthma_total = asthma_emergency_department_visits_children_0_to_4_yrs_old + asthma_emergency_department_visits_children_5_to_14_yrs_old,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total))

## Join all together
tree_density_total = tree_density %>%
  select(geo_entity_id=uhf42_code, tree_density) %>%
  distinct()

final_df = left_join(asthma_air_poverty, tree_density_total)


## Asthma_map

asthma_map = final_df %>%
  dplyr::select (id = geo_entity_id, asthma = asthma_total,geo_entity_name) 
names(final_df)

### Write a function to remove grid and axis

theme_nothing <- function(base_size = 12, legend = TRUE){
  if(legend){
    theme(
      axis.text =          element_blank(),
      axis.title =         element_blank(),
      panel.background =   element_blank(),
      panel.grid.major =   element_blank(),
      panel.grid.minor =   element_blank(),
      axis.ticks.length =  unit(0, "cm"),
      panel.spacing =      unit(0, "lines"),
      plot.margin =        unit(c(0, 0, 0, 0), "lines")
    )
  } else {
    theme(
      line =               element_blank(),
      rect =               element_blank(),
      text =               element_blank(),
      axis.ticks.length =  unit(0, "cm"),
      legend.position =    "none",
      panel.spacing =      unit(0, "lines"),
      plot.margin =        unit(c(0, 0, 0, 0), "lines")
    )
  }
}


```



Column {.tabset data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

cnames = aggregate(cbind(x, y) ~ id, data=map_data, FUN=mean)
cnames = left_join(cnames,asthma_map, by = "id")
cnames = cnames[-1,]
map = ggplot(asthma_map) +
    geom_map(aes(map_id = id, fill = asthma), color = "white", map = map_data)  +
    scale_fill_gradient(high = "#c51b8a",low = "#fde0dd", guide = "colorbar", name="Visits") +
    expand_limits(map_data) +
  geom_text(data = cnames, aes(x = x, y = y, label = geo_entity_name), size = 2) + theme_void()+
  theme(legend.justification=c(1,0), legend.position=c(1,0)) +
    theme_nothing()

  ggplotly(map) %>%
  layout(hoverlabel = list(bgcolor = "white", 
                              font = list(family = "Calibri", 
                                          size = 14, 
                                          color = "black")))

```


### Chart B

```{r}
ax = list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)

#asthma 0-4 and asthma 5-14 in each UHF42
final_df %>% 
  gather(key = "asthma_age",
         value  = rate ,
         asthma_emergency_department_visits_children_0_to_4_yrs_old,
         asthma_emergency_department_visits_children_5_to_14_yrs_old) %>% 
  
plot_ly(x= ~rate, y= ~geo_entity_name, color = ~asthma_age, type = 'bar',orientation = "h") %>%
  layout(
         yaxis = ax,
         xaxis = list(title = "Asthma rate"),
        legend = list(x = 0.3, y = 0.01)
  )
```

Column {data-width=550}
-----------------------------------------------------------------------
### Chart C

```{r}

```


### Chart D {.tabset}

```{r}


```

### Chart E 

```{r}


```
