---
title: "final report"
author: "Jingwei Ren"
date: "12/2/2018"
output: html_document
---

## final report

## motivation

Over the past decades, the prevalence of asthma has increased in the urban areas with the potential effects of airflow, air quality and production of aeroallergens. Asthma is the most prevalent chronic disease among children. The disease can make breathing difficult and trigger coughing, wheezing and shortness of breath by the presence of extra mucus in narrow airways. Data on the influence of green spaces on asthma in children are inconstant. Previous research that did in Kaunas, Lithuania showed a positive association between the level of the surrounding greenness and risk of asthma in children. Their study suggested that high exposure to green spaces may increase the risk of allergic conditions and the prevalence of asthma through the effect of pollen. Another ecological design study did in New York City observed an inverse association between street tree density and the prevalence of asthma. Others have reported no relationships between greenery densities, canopy cover and asthma.

Our goal was to investigate the association between tree densities and asthma among children in New York City, including variables like poverties, smoking, air quality factors like fine particulate matter (PM2.5), and ambient concentrations of sulfur dioxide (SO2).


## related work

Asthma infection has been an issue for a long time. Inconsistent associations between urban greenery and childhood asthma had stimulated studies on the relations between those two factors. Scientific reviews related to tree densities and asthma rate are here: [Children Living in areas with more street tress have lower prevalence of asthma](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3415223/), [Associations between neighborhood greenness and asthma in preschool children in Kaunas,Lithuania](https://repository.lsmuni.lt/bitstream/handle/1/1787/27067890.pdf?sequence=1&isAllowed=y) and [Risks and benefits of Green Spaces for children: A Cross-Sectional Study of Associations with Sedentary Behavior, Obesity, Asthma, and Allergy](https://ehp.niehs.nih.gov/doi/10.1289/ehp.1308038).


## Initial Questions


Our initial questions was whether there is an association between tree densities and asthma among children in New York City based on 42 different neighborhoods.

Furthermore, we investigated the relationships between asthma and other factors, like air qualities, factors like fine particulate matter (PM2.5), and ambient concentrations of sulfur dioxide (SO2)), poverties, and smoking. Trades of asthma changes were considered for two different sample groups (children from 0 to 4 years old and children from 5 to 14 years old) from 1998 to 2016.

We were also interested in the association between tree densities in 42 different neighborhoods and air quality factors.





