<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title></title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Data.html">Data</a>
</li>
<li>
  <a href="dashboRD.html">Dashboard</a>
</li>
<li>
  <a href="https://treeandasthma.shinyapps.io/asthma_tree/">Shiny</a>
</li>
<li>
  <a href="map.Rmd">
    <span class="fab fa fab fa-youtube"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/Adashaw77/p8105_final_project/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">




</div>


<div id="final-report" class="section level1">
<h1>final report</h1>
<p>Jingwei Ren, Baoyi Shi, Xinyao Wu, Qi Shao 12/2/2018</p>
<div id="motivation" class="section level2">
<h2>motivation</h2>
<p>Over the past decades, the prevalence of asthma has increased in the urban areas with the potential effects of airflow, air quality and production of aeroallergens. Asthma is the most prevalent chronic disease among children. The disease can make breathing difficult and trigger coughing, wheezing and shortness of breath by the presence of extra mucus in narrow airways. Data on the influence of green spaces on asthma in children are inconstant. Previous research that did in Kaunas, Lithuania showed a positive association between the level of the surrounding greenness and risk of asthma in children. Their study suggested that high exposure to green spaces may increase the risk of allergic conditions and the prevalence of asthma through the effect of pollen. Another ecological design study did in New York City observed an inverse association between street tree density and the prevalence of asthma. Others have reported no relationships between greenery densities, canopy cover and asthma.</p>
<p>Our goal was to investigate the association between tree densities and asthma among children in New York City, including variables like poverties and air quality factors like fine particulate matter (PM2.5), and ambient concentrations of sulfur dioxide (SO2).</p>
</div>
<div id="related-work" class="section level2">
<h2>related work</h2>
<p>Asthma infection has been an issue for a long time. Inconsistent associations between urban greenery and childhood asthma had stimulated studies on the relations between those two factors. Scientific reviews related to tree densities and asthma rate are here: <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3415223/">Children Living in areas with more street tress have lower prevalence of asthma</a>, <a href="https://repository.lsmuni.lt/bitstream/handle/1/1787/27067890.pdf?sequence=1&amp;isAllowed=y">Associations between neighborhood greenness and asthma in preschool children in Kaunas,Lithuania</a> and <a href="https://ehp.niehs.nih.gov/doi/10.1289/ehp.1308038">Risks and benefits of Green Spaces for children: A Cross-Sectional Study of Associations with Sedentary Behavior, Obesity, Asthma, and Allergy</a>.</p>
</div>
<div id="initial-questions" class="section level2">
<h2>Initial Questions</h2>
<p>Our initial questions was whether there is an association between tree densities and asthma among children in New York City based on 42 different neighborhoods.</p>
<p>Furthermore, we investigated the relationships between asthma and other factors, like poverties and air qualities, factors like fine particulate matter (PM2.5), and ambient concentrations of sulfur dioxide (SO2)). We were also interested in the association between tree densities in 42 different neighborhoods and air quality factors.</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>Our GitHub repo of the steps in this analysis can be found <a href="https://github.com/Adashaw77/p8105_final_project/blob/master/final.Rmd">here</a>.</p>
<p>The original tree data includes variables: zip code of each neighborhoods, boroname, tree’s diameter, status(alive and dead), health, spc_common (tree species) and tree’s latitude and longitude.</p>
<p>The asthma dataset has a total 16 variables and it includes important variables like neighborhoods, asthma rate for children from 0 to 4 years old and children from 5 to 14 years old, so2 level, poverty percent, percent of the children under 5 years living in the poverty areas, tree’s density and total asthma rate.</p>
<div id="data-source" class="section level3">
<h3>Data Source</h3>
<p>All data about asthma, poverty and air qualities was retrieved from NYC health (<a href="http://a816-dohbesp.nyc.gov/IndicatorPublic/PublicTracking.aspx" class="uri">http://a816-dohbesp.nyc.gov/IndicatorPublic/PublicTracking.aspx</a>)</p>
<p>All data related to trees was retrieved from NYC open data (<a href="https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/pi5s-9p35" class="uri">https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/pi5s-9p35</a>)</p>
<p>All neighborhood data was retrieved from (<a href="http://www.infoshare.org/misc/UHF.pdf" class="uri">http://www.infoshare.org/misc/UHF.pdf</a>)</p>
</div>
<div id="scraping-method-cleaning" class="section level3">
<h3>scraping method, cleaning</h3>
<pre class="r"><code>#import and tidy tree data
tree_df = read_csv(&quot;./data/2015StreetTreesCensus_TREES.csv&quot;) %&gt;%
  janitor::clean_names() %&gt;%
  filter(status == &quot;Alive&quot;) </code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   zipcode = col_integer(),
##   boroname = col_character(),
##   tree_dbh = col_integer(),
##   status = col_character(),
##   health = col_character(),
##   spc_common = col_character(),
##   Latitude = col_double(),
##   longitude = col_double()
## )</code></pre>
<pre class="r"><code>zipcode_uhf42 = read_excel(&quot;./data/Zipcode_UHF42.xlsx&quot;) %&gt;%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %&gt;%
   select(-zipcode_no, uhf42_name) %&gt;%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = &quot;zipcode&quot;) 

mydat = rgdal::readOGR(&quot;./UHF42/UHF_42_DOHMH.shp&quot;)</code></pre>
<pre><code>## OGR data source with driver: ESRI Shapefile 
## Source: &quot;/Users/wuxinyao/Desktop/p8105_final_project/UHF42/UHF_42_DOHMH.shp&quot;, layer: &quot;UHF_42_DOHMH&quot;
## with 43 features
## It has 8 fields</code></pre>
<pre class="r"><code>area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %&gt;%
  filter(is.na(uhf42_code) == FALSE)

tree_df = left_join(tree_df, area, by = &quot;uhf42_code&quot;)

#tree density element is added
tree_density = tree_df %&gt;%
  group_by(boroname, uhf42_name, uhf42_code, area) %&gt;%
  dplyr::summarize(tree_total = n()) %&gt;%
  filter(is.na(uhf42_name) == FALSE) %&gt;%
  group_by(uhf42_name) %&gt;%
  dplyr::mutate(tree_density = tree_total/area) %&gt;%
  ungroup() %&gt;%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))</code></pre>
<pre class="r"><code># import and tidy astham data

asthma_air_poverty = read_csv(&quot;./data/asthma_pollutes_poverty.csv&quot;) %&gt;%
  select(geo_entity_id, geo_entity_name, name, data_value) %&gt;%
  filter(is.na(geo_entity_id) == FALSE) %&gt;%
  spread(key = name, value = data_value) %&gt;%
  janitor::clean_names() %&gt;%
  select(poverty, children_under_5_years_old_in_poverty, everything()) %&gt;%
  mutate(asthma_total = asthma_emergency_department_visits_children_0_to_4_yrs_old + asthma_emergency_department_visits_children_5_to_14_yrs_old,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total))</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   `Unique Id` = col_character(),
##   indicator_id = col_integer(),
##   geo_type_id = col_integer(),
##   measurement_type_id = col_integer(),
##   internal_id = col_integer(),
##   subtopic_id = col_integer(),
##   name = col_character(),
##   Measure = col_character(),
##   geo_type_name = col_character(),
##   description = col_character(),
##   geo_entity_id = col_integer(),
##   geo_entity_name = col_character(),
##   year_description = col_character(),
##   data_value = col_double(),
##   message = col_character()
## )</code></pre>
<pre class="r"><code>tree_density_total = tree_density %&gt;%
  select(boroname, geo_entity_id=uhf42_code, tree_density) %&gt;%
  distinct()

final_df = left_join(asthma_air_poverty, tree_density_total)</code></pre>
<pre><code>## Joining, by = &quot;geo_entity_id&quot;</code></pre>
</div>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory analysis:</h2>
<div id="asthma-visualizations" class="section level3">
<h3>Asthma Visualizations</h3>
</div>
<div id="step-one" class="section level3">
<h3>Step one</h3>
<pre class="r"><code>#plot between asthma and tree
final_asthma_df = gather(final_df, key = asthma_age, value = rate, asthma_emergency_department_visits_children_0_to_4_yrs_old:asthma_emergency_department_visits_children_5_to_14_yrs_old) %&gt;%
  gather(key = poverty_age, value = poverty, poverty:children_under_5_years_old_in_poverty) %&gt;%
  filter((asthma_age == &quot;asthma_emergency_department_visits_children_5_to_14_yrs_old&quot;&amp;poverty_age == &quot;poverty&quot;)|(asthma_age == &quot;asthma_emergency_department_visits_children_0_to_4_yrs_old&quot;&amp; poverty_age == &quot;children_under_5_years_old_in_poverty&quot;))

#plot between tree and astham rate
ggplot(final_asthma_df) +
  geom_point(aes(x = tree_density, y = rate, color = asthma_age)) +
   geom_smooth(aes(x = tree_density, y = rate, color = asthma_age), method = &quot;lm&quot;,se = F) +
   labs(
    title = &quot;plot 1: Asthma and Tree Density&quot;,
    x = &quot;Tree Density&quot;,
    y = &quot;Asthma Rate&quot;
  ) +
   theme(legend.position = &quot;bottom&quot;) +
   guides(color = guide_legend(nrow = 2)) +
   scale_color_hue(name = &quot;Age&quot;)</code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-4-1.png" />

</div>
<p>This plot 1 showed the relationship between asthma and tree. Visually, there was a positive association between tree density and astham rate.</p>
</div>
<div id="step-two" class="section level3">
<h3>Step two</h3>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<p>9b3979ef49895e8f5e21553305a8014306fd4d43 Other factors may also impact the astham rate. We made plots showing the association between astham and air qualities (fine particulate matter (PM2.5), and ambient concentrations of sulfur dioxide (SO2) ) and the association between asthma and poverty rate.</p>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
<pre class="r"><code>#plot between asthma and so2
ggplot(final_asthma_df) +
   geom_point(aes(x = sulfur_dioxide_so2, y = rate, color = asthma_age))+
   geom_smooth(aes(x = sulfur_dioxide_so2, y = rate, color = asthma_age), method = &quot;lm&quot;, se = F) +
   labs(
    title = &quot;plot 2: Asthma and Sulfur Dioxide&quot;,
    x = &quot;Sulfur Dioxide Average&quot;,
    y = &quot;Asthma Rate&quot;
  ) +
   theme(legend.position = &quot;bottom&quot;) +
   guides(color = guide_legend(nrow = 2)) +
   scale_color_hue(name = &quot;Age&quot;)</code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-5-1.png" />

</div>
<pre class="r"><code># plot asthma and pm2.5
ggplot(final_asthma_df) +
   geom_point(aes(x = fine_particulate_matter_pm2_5, y = rate, color = asthma_age))+
   geom_smooth(aes(x = fine_particulate_matter_pm2_5, y = rate, color = asthma_age), method = &quot;lm&quot;, se = F) +
   labs(
    title = &quot;plot 3: Asthma and PM2.5&quot;,
    x = &quot;PM2.5 Average&quot;,
    y = &quot;Asthma Rate&quot;
  ) +
   theme(legend.position = &quot;bottom&quot;) +
   guides(color = guide_legend(nrow = 2)) +
   scale_color_hue(name = &quot;Age&quot;)</code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-5-2.png" />

</div>
<pre class="r"><code># plot between asthma and poverty
ggplot(final_asthma_df) +
   geom_point(aes(x = poverty, y = rate, color = asthma_age))+
   geom_smooth(aes(x = poverty, y = rate, color = asthma_age), method = &quot;lm&quot;, se = F) +
   labs(
    title = &quot;plot 4: Asthma and Poverty&quot;,
    x = &quot;Poverty Percent&quot;,
    y = &quot;Asthma Rate&quot;
  ) +
   theme(legend.position = &quot;bottom&quot;) +
   guides(color = guide_legend(nrow = 2)) +
   scale_color_hue(name = &quot;Age&quot;)</code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-5-3.png" />

</div>
<p>plot2 showed the relationship between asthma rate and so2. plot3 showed the relationship between astham rate rate and pM.25 plot4 showed the relationship between asthma and poverty. Visually, there was a positive association between astham rate and SO2, PM 2.5 and poverty level.</p>
<div id="step-three" class="section level4">
<h4>step three</h4>
</div>
</div>
<div id="step-three-1" class="section level3">
<h3>Step three</h3>
<p>We are interested in seeing whether asthma rate is different between children from 0 to 4 years old and children from 5 to 14 years old in 42 neighborhoods in new york city.</p>
<pre class="r"><code>#plot between asthma 0-4 and asthma 5-14 in each UHF42
ggplot(final_asthma_df) +
  geom_bar(aes(x = geo_entity_name, y = rate, fill = asthma_age), stat = &quot;identity&quot;, position = &quot;dodge&quot;) +
   labs(
    title = &quot;plot 5: Asthma Rate In Each Entity&quot;,
    x = &quot;Entity Name&quot;,
    y = &quot;Asthma Rate&quot;
  ) +
   theme(legend.position = &quot;bottom&quot;, axis.text.x = element_text(angle = 75, hjust = 1)) +
   guides(fill = guide_legend(nrow = 2)) +
   scale_fill_hue(name = &quot;Age&quot;) </code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-6-1.png" />

</div>
<p>Plot 5 showed that children from 0 to 4 years have higher asthma rate compared to children from 5 to 14 years old.</p>
</div>
</div>
<div id="tree-visualizations" class="section level2">
<h2>Tree Visualizations</h2>
<p>We were also interested testing the association between tree density and air quality factors.</p>
<pre class="r"><code>#plot between tree and SO2
ggplot(final_asthma_df) +
  geom_point(aes(x = sulfur_dioxide_so2, y = tree_density)) +
  geom_smooth(aes(x = sulfur_dioxide_so2, y = tree_density), method = &quot;lm&quot;, se = F) +
   labs(
    title = &quot;plot 6: Tree Density and Sulfur Dioxide&quot;,
    x = &quot;Sulfur Dioxide Average&quot;,
    y = &quot;Tree Density&quot;
  ) </code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-7-1.png" />

</div>
<pre class="r"><code>#plot between tree and pm2.5
ggplot(final_asthma_df) +
  geom_point(aes(x = fine_particulate_matter_pm2_5, y = tree_density)) +
  geom_smooth(aes(x = fine_particulate_matter_pm2_5, y = tree_density), method = &quot;lm&quot;, se = F) +
   labs(
    title = &quot;plot 7: Tree Density and PM2.5&quot;,
    x = &quot;PM2.5 Average&quot;,
    y = &quot;Tree Density&quot;
  ) </code></pre>
<div class="figure">
<img src="finalreport_files/figure-markdown_github/unnamed-chunk-7-2.png" />

</div>
<p>plot 6 showed the association between tree density and so2. plot 7 showed the association between tree density and pm 2.5 Visually, there was a positive association between tree density and air quality factors.</p>
</div>
<div id="statistical-analyses" class="section level2">
<h2>Statistical analyses</h2>
<pre class="r"><code># mlr showing the relationship between asthma rate of kids from 0 to 4 years and tree density, so2 levels, percent of the children under 5 years living in the poverty areas
summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~tree_density+sulfur_dioxide_so2+children_under_5_years_old_in_poverty,data=final_df)) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable()</code></pre>
<table>
<colgroup>
<col width="45%" />
<col width="15%" />
<col width="14%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-103.55417</td>
<td align="right">7.107578e+01</td>
<td align="right">-1.4569545</td>
<td align="right">0.1527456</td>
</tr>
<tr class="even">
<td align="left">tree_density</td>
<td align="right">-450005.47197</td>
<td align="right">7.087065e+05</td>
<td align="right">-0.6349673</td>
<td align="right">0.5289775</td>
</tr>
<tr class="odd">
<td align="left">sulfur_dioxide_so2</td>
<td align="right">192.94852</td>
<td align="right">6.144257e+01</td>
<td align="right">3.1403066</td>
<td align="right">0.0031272</td>
</tr>
<tr class="even">
<td align="left">children_under_5_years_old_in_poverty</td>
<td align="right">11.17321</td>
<td align="right">1.438942e+00</td>
<td align="right">7.7648807</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<pre class="r"><code># mlr howing the relationship between asthma rate of kids from 5 to 14 years and tree density, so2 levels, poverty levels

summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~tree_density+sulfur_dioxide_so2+poverty,data=final_df)) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-82.55365</td>
<td align="right">5.019181e+01</td>
<td align="right">-1.6447634</td>
<td align="right">0.1076654</td>
</tr>
<tr class="even">
<td align="left">tree_density</td>
<td align="right">-471392.09498</td>
<td align="right">4.963879e+05</td>
<td align="right">-0.9496446</td>
<td align="right">0.3478574</td>
</tr>
<tr class="odd">
<td align="left">sulfur_dioxide_so2</td>
<td align="right">122.64218</td>
<td align="right">4.405184e+01</td>
<td align="right">2.7840421</td>
<td align="right">0.0080856</td>
</tr>
<tr class="even">
<td align="left">poverty</td>
<td align="right">12.87822</td>
<td align="right">1.587895e+00</td>
<td align="right">8.1102445</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<p>Based on the multiple linear regression models, all the factors are significant except tree density ( p value is 0.86, 0.64). This indicated that there are associations between asthma rate of kids and so2 and poverty levels. model one: asthma = -103.55-450005 tree_density +192SO2+ 11.17poverty model two: asthma = -82.55 -471392 tree_density+ 122SO2+12.87poverty</p>
</div>
<div id="additional-analysis" class="section level2">
<h2>Additional analysis</h2>
<p>We tested the association between astham rate and all pollutes including ozone, black carbon, PM 2.5, NO, NO2, SO2.</p>
<pre class="r"><code>#SLR:choose the pollutes associated with asthma
o3_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~ozone_o3, data=final_df))$coefficients[2,4]

o3_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~ozone_o3, data=final_df))$coefficients[2,4]

black_carbon_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~black_carbon, data=final_df))$coefficients[2,4]

black_carbon_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~black_carbon, data=final_df))$coefficients[2,4]

pm2_5_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~fine_particulate_matter_pm2_5, data=final_df))$coefficients[2,4]

pm2_5_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~fine_particulate_matter_pm2_5, data=final_df))$coefficients[2,4]

no_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~nitric_oxide_no, data=final_df))$coefficients[2,4]

no_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~nitric_oxide_no, data=final_df))$coefficients[2,4]

no2_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~nitrogen_dioxide_no2, data=final_df))$coefficients[2,4]

no2_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~nitrogen_dioxide_no2, data=final_df))$coefficients[2,4]

so2_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~sulfur_dioxide_so2, data=final_df))$coefficients[2,4]

so2_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~sulfur_dioxide_so2, data=final_df))$coefficients[2,4]

data.frame(Pollute = c(&quot;Ozone&quot;, &quot;Black Carbon&quot;, &quot;PM2.5&quot;, &quot;NO&quot;, &quot;NO2&quot;, &quot;SO2&quot;),
                     P_value1 = c(o3_p1, black_carbon_p1, pm2_5_p1, no_p1, no2_p1, so2_p1),
                     P_value2 = c(o3_p2, black_carbon_p2, pm2_5_p2, no_p2, no2_p2, so2_p2)) %&gt;%
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Pollute</th>
<th align="right">P_value1</th>
<th align="right">P_value2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Ozone</td>
<td align="right">0.893</td>
<td align="right">0.376</td>
</tr>
<tr class="even">
<td align="left">Black Carbon</td>
<td align="right">0.569</td>
<td align="right">0.220</td>
</tr>
<tr class="odd">
<td align="left">PM2.5</td>
<td align="right">0.678</td>
<td align="right">0.265</td>
</tr>
<tr class="even">
<td align="left">NO</td>
<td align="right">0.490</td>
<td align="right">0.883</td>
</tr>
<tr class="odd">
<td align="left">NO2</td>
<td align="right">0.758</td>
<td align="right">0.328</td>
</tr>
<tr class="even">
<td align="left">SO2</td>
<td align="right">0.023</td>
<td align="right">0.006</td>
</tr>
</tbody>
</table>
<pre class="r"><code>#based on p values, we choose SO2</code></pre>
<p>The result showed that only SO2 had an association with asthma, since the p value is lower than 0.05. All the other air quality factors are not significantly related to children asthma rate.</p>
<p>We did a paired T test to test if there is significant difference between asthma rate of 0-4 and that of 5-14</p>
<pre class="r"><code>#Paired T test to test if there is significant difference between asthma rate of 0-4 and that of 5-14
t.test(final_df$asthma_emergency_department_visits_children_0_to_4_yrs_old, final_df$asthma_emergency_department_visits_children_5_to_14_yrs_old, paired=T) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">57.01778</td>
<td align="right">4.761863</td>
<td align="right">2.11e-05</td>
<td align="right">44</td>
<td align="right">32.88609</td>
<td align="right">81.14946</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
</tbody>
</table>
<p>The T test result showed that there is significant difference between children asthma rate of 0-4 and that of 5-14. P value is 2.11e-05, lower than 0.05.</p>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>Our main goal is to discuss the relationship between tree density in New York City and children asthma rate in 2015. We built two multilinear regression models, investigating the relationship between asthma rate and tree density, SO2 and poverty level for children from 0 to 4 years old and children from 5 to 14 years old. The result showed that exposure to air pollution (SO2) (P-value = 0.048, 0.0116) and increased poverty level(p-value = 6.41e-09,2.83e-09) could contribute to excess asthma in urban areas. All the factors are significant except tree density ( p-value = 0.86, 0.64). We listed some possible reasons that explained why no obvious association was shown between tree density and asthma. One possible explanation is the season. In the spring and summer months, increasing tree densities might have a positive impact on asthma rate. Pollen could be an allergen that gives some people sneezing fits and watery eyes, which could indirectly cause an asthma attack in others. Certain trees like Ash, Birch, and Oak could cause aggravate respiratory allergies. However, in the fall and winter months, increasing tree densities might decrease the asthma rate through the effect on local air quality. Those two situations might counteract each other and result in the conclusion that overall, there was no association between tree density in New York City and children asthma rate in 2015. Other factors might also influence the asthma rate, including sociodemographic characteristics, population density and hospitals amount in the neighborhood. After adjustment, the association between tree density and hospitalizations as a result of asthma might no longer significant.</p>
<p>We were also interested to see whether there was a difference in asthma rate between children from 0 to 4 years old and children from 5 to 14 years old. The result from plot 5 showed that children from 0 to 4 years have a higher asthma rate compared to children from 5 to 14 years old. The T-test also proved that there is a significant difference between children asthma rate of 0-4 and that of 5-14. (P value = 2.11e-05). A positive relationship between tree density and air quality factors in 42 neighborhood in New York city was reported. Tree density increases as CO2 and PM 2.5 levels increase. One possible explanation for this could be that people’s awareness of environment increases as the air quality in one area decreases. Therefore, we saw a positive result. We would expect to see a negative association. In order to verify this, we could make plots detecting the change of air quality’s levels throughout a couple of years. Increasing tree densities might help to decrease air quality’s levels through a long-term process.</p>
<p>In conclusion, we found out that there is no association between tree density and asthma rate based on our data set. If more variables are included in the future, we would expect to see that afforestation in low-income communities will help improve air-quality and thus decrease the risk of child asthma over a long-term period</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
