---
title: "tree and asthma"
author: "Baoyi Shi"
date: "2018年12月4日"
output: html_document
---

```{r }
library(tidyverse)
library(dplyr)
library(readr)
library(ggplot2)
library(readxl)
library(rvest)
library(httr)
```

```{r }
tree_df = GET("https://data.cityofnewyork.us/api/views/5rq2-4hqu/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")

tree_df = tree_df %>%
  janitor::clean_names() %>%
  filter(status == "Alive") %>%
  select(zipcode, latitude, longitude)

download.file("https://raw.githubusercontent.com/BS1125/project_data/master/Zipcode_UHF42.xlsx",mode = "wb",destfile = "Zipcode_UHF42.xlsx")

zipcode_uhf42 = read_excel("Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = "zipcode") 

download.file("https://catharob.carto.com/api/v2/sql?filename=uhf_42_dohmh_2009&q=SELECT+*+FROM+(select+*+from+public.uhf_42_dohmh_2009)+as+subq+&format=csv&bounds=&api_key=&skipfields=the_geom_webmercator",destfile = "UHF_42.csv")

area = read_csv("UHF_42.csv") %>%
  filter(uhfcode != 0) %>%
  select(uhf42_code = uhfcode, area = shape_area)

tree_df = left_join(tree_df, area, by = "uhf42_code")
```

```{r }
#tree density
tree_density = tree_df %>%
  group_by(uhf42_name, uhf42_code, area) %>%
  dplyr::summarize(tree_total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  group_by(uhf42_name) %>%
  dplyr::mutate(tree_density = tree_total/area) %>%
  ungroup() %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))
```

```{r }
#read and tidy data
download.file("https://raw.githubusercontent.com/BS1125/project_data/master/asthma_pollutes_poverty.csv",mode = "wb",destfile = "asthma_air_poverty.csv")

asthma_air_poverty = read_csv("asthma_air_poverty.csv") %>%
  select(geo_entity_id, geo_entity_name, name, data_value) %>%
  filter(is.na(geo_entity_id) == FALSE) %>%
  spread(key = name, value = data_value) %>%
  janitor::clean_names() %>%
  select(poverty, children_under_5_years_old_in_poverty, everything()) %>%
  mutate(asthma_total = asthma_emergency_department_visits_children_0_to_4_yrs_old + asthma_emergency_department_visits_children_5_to_14_yrs_old,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total))

tree_density_total = tree_density %>%
  select(geo_entity_id=uhf42_code, tree_density) %>%
  distinct()

final_df = left_join(asthma_air_poverty, tree_density_total)
```

```{r }
#SLR:choose the pollutes associated with asthma
o3_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~ozone_o3, data=final_df))$coefficients[2,4]

o3_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~ozone_o3, data=final_df))$coefficients[2,4]

black_carbon_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~black_carbon, data=final_df))$coefficients[2,4]

black_carbon_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~black_carbon, data=final_df))$coefficients[2,4]

pm2_5_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~fine_particulate_matter_pm2_5, data=final_df))$coefficients[2,4]

pm2_5_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~fine_particulate_matter_pm2_5, data=final_df))$coefficients[2,4]

no_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~nitric_oxide_no, data=final_df))$coefficients[2,4]

no_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~nitric_oxide_no, data=final_df))$coefficients[2,4]

no2_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~nitrogen_dioxide_no2, data=final_df))$coefficients[2,4]

no2_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~nitrogen_dioxide_no2, data=final_df))$coefficients[2,4]

so2_p1 = summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~sulfur_dioxide_so2, data=final_df))$coefficients[2,4]

so2_p2 = summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~sulfur_dioxide_so2, data=final_df))$coefficients[2,4]

data.frame(Pollute = c("Ozone", "Black Carbon", "PM2.5", "NO", "NO2", "SO2"),
                     P_value1 = c(o3_p1, black_carbon_p1, pm2_5_p1, no_p1, no2_p1, so2_p1),
                     P_value2 = c(o3_p2, black_carbon_p2, pm2_5_p2, no_p2, no2_p2, so2_p2)) %>%
  knitr::kable(digits = 3)
#based on p values, we choose SO2
```

```{r }
#MLR
summary(lm(asthma_emergency_department_visits_children_0_to_4_yrs_old~tree_density+sulfur_dioxide_so2+children_under_5_years_old_in_poverty,data=final_df)) %>%
  broom::tidy() %>%
  knitr::kable()

summary(lm(asthma_emergency_department_visits_children_5_to_14_yrs_old~tree_density+sulfur_dioxide_so2+poverty,data=final_df)) %>%
  broom::tidy() %>%
  knitr::kable()
```

```{r }
final_asthma_df = gather(final_df, key = asthma_age, value = rate, asthma_emergency_department_visits_children_0_to_4_yrs_old:asthma_emergency_department_visits_children_5_to_14_yrs_old) %>%
  gather(key = poverty_age, value = poverty, poverty:children_under_5_years_old_in_poverty) %>%
  filter((asthma_age == "asthma_emergency_department_visits_children_5_to_14_yrs_old"&poverty_age == "poverty")|(asthma_age == "asthma_emergency_department_visits_children_0_to_4_yrs_old"& poverty_age == "children_under_5_years_old_in_poverty"))

#asthma and so2
ggplot(final_asthma_df) +
   geom_point(aes(x = sulfur_dioxide_so2, y = rate, color = asthma_age))+
   geom_smooth(aes(x = sulfur_dioxide_so2, y = rate, color = asthma_age), method = "lm", se = F) +
   labs(
    title = "Asthma and Sulfur Dioxide",
    x = "Sulfur Dioxide Annual Average",
    y = "Asthma Rate"
  ) +
   theme(legend.position = "bottom") 

#asthma and pm2.5
ggplot(final_asthma_df) +
   geom_point(aes(x = fine_particulate_matter_pm2_5, y = rate, color = asthma_age))+
   geom_smooth(aes(x = fine_particulate_matter_pm2_5, y = rate, color = asthma_age), method = "lm", se = F) +
  theme(legend.position = "bottom")

#asthma and poverty
ggplot(final_asthma_df) +
   geom_point(aes(x = poverty, y = rate, color = asthma_age))+
   geom_smooth(aes(x = poverty, y = rate, color = asthma_age), method = "lm", se = F) +
  theme(legend.position = "bottom")

#asthma and tree
ggplot(final_asthma_df) +
  geom_point(aes(x = tree_density, y = rate, color = asthma_age)) +
   geom_smooth(aes(x = tree_density, y = rate, color = asthma_age), method = "lm",se = F) +
  theme(legend.position = "bottom")

#tree and SO2
ggplot(final_asthma_df) +
  geom_point(aes(x = sulfur_dioxide_so2, y = tree_density)) +
  geom_smooth(aes(x = sulfur_dioxide_so2, y = tree_density), method = "lm", se = F)

#tree and pm2.5
ggplot(final_asthma_df) +
  geom_point(aes(x = fine_particulate_matter_pm2_5, y = tree_density)) +
  geom_smooth(aes(x = fine_particulate_matter_pm2_5, y = tree_density), method = "lm", se = F) +
   labs(
    title = "Tree Density and PM2.5",
    x = "PM2.5 Average",
    y = "Tree Density"
  ) 


#asthma 0-4 and asthma 5-14 in each UHF42
ggplot(final_asthma_df) +
  geom_bar(aes(x = geo_entity_name, y = rate, fill = asthma_age), stat = "identity", position = "dodge") +
   labs(
    title = "Asthma Rate In Each Entity",
    x = "Entity Name",
    y = "Asthma Rate"
  ) +
   theme(legend.position = "bottom", axis.text.x = element_text(angle = 75, hjust = 1)) +
   guides(fill = guide_legend(nrow = 2)) +
   scale_fill_hue(name = "Age") 

#Paired T test to test if there is significant difference between asthma rate of 0-4 and that of 5-14
t.test(final_df$asthma_emergency_department_visits_children_0_to_4_yrs_old, final_df$asthma_emergency_department_visits_children_5_to_14_yrs_old, paired=T) %>%
  broom::tidy() %>%
  knitr::kable()
```


