---
title: "Tidy"
author: "Qi Shao"
date: "12/2/2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plyr)
library(readr)
```


```{r}

children1 = read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Asthma Hospitalizations (Children 0 to 4 Yrs Old)") %>%
  filter(Measure == "Rate") %>%
  dplyr::select(name,geo_entity_name,year_description,data_value) 
  
ggplot(children1, aes(x = year_description, y = data_value)) + 
  geom_boxplot()+
  labs(
    title = "year vs asthma Children 0 to 4  Yrs Old ",
    x = "year",
    y = "asthma"
  )


children2 = read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Asthma Hospitalizations (Children 5 to 14 Yrs Old)") %>%
  filter(Measure == "Rate") %>%
  dplyr::select(name,geo_entity_name,year_description,data_value) 
  
ggplot(children2, aes(x = year_description, y = data_value)) + 
  geom_boxplot()+
  labs(
    title = "year vs asthma Children 5 to 14 Yrs Old ",
    x = "year",
    y = "asthma"
  )


asthma_air = read_csv("./data/asthma_air/Data.csv") %>%
  filter(str_detect(year_description, "^20|^An")) %>%
  mutate(year_description = str_remove(year_description, "Annual Average ")) %>%
    filter(year_description == 2015)

sulfur_dioxide= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Sulfur Dioxide (SO2)") %>%
  filter(year_description == "Winter 2014-15")

ozone= read_csv("./data/asthma_air/Data.csv") %>%
  filter(name == "Ozone (O3)") %>%
  filter(year_description == "Summer 2015")

poverty= read_csv("./data/poverty/Data.csv") %>%
  filter(year_description == "2011-15" )

smoke = read_csv("./data/smoking_exer/Data.csv") %>%
  filter(year_description == "2015" )

data = rbind(asthma_air,sulfur_dioxide,ozone, poverty, smoke)
  


asthma_air1 = data %>%
 dplyr::select(name, description, Measure, geo_entity_name, geo_entity_id, year = year_description, data_value) %>%
  janitor::clean_names() %>% 
  filter(measure %in% c("Mean", "Rate", "Number", "Percent", "Age-Adjusted Percent", "Age-Adjusted Rate ")) %>%
  mutate(name_measure=str_c(name,"-",measure)) %>%
  dplyr::select(-name, -measure, -description, -year) %>%
  spread(key = name_measure, value = data_value) 

names(asthma_air1)
```
