---
title: "tree"
author: "Baoyi Shi"
date: "2018年12月2日"
output: html_document
---

```{r tree,warning =FALSE}
library(tidyverse)
library(dplyr)
library(readr)
library(readxl)
library(ggplot2)
library(readxl)
```


```{r }
#import and tidy tree data
tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  janitor::clean_names() %>%
  filter(status == "Alive")

zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = "zipcode") 

mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")

area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_code) == FALSE)

tree_df = left_join(tree_df, area, by = "uhf42_code")
```


```{r }
#tree density
tree_density = tree_df %>%
  group_by(uhf42_name, area, health) %>%
  dplyr::summarize(health_total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  group_by(uhf42_name) %>%
  dplyr::mutate(total = sum(health_total),
                tree_density = total/area,
                health_tree_density = health_total/area) %>%
  ungroup() %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))
```

```{r }
#proportion of each health status in UHF42
ggplot(aes(x = uhf42_name), data = tree_df) +
  geom_bar(position="fill", aes(fill = health)) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) 
```



```{r warning=F}
#import tree data, retain only trees alive and good to health
tree_df = read_csv("./data/2015StreetTreesCensus_TREES.csv") %>%
  janitor::clean_names() %>%
  filter(status == "Alive", health == "Good") 
```

```{r warning=F}
#compute the total tree number of each boro
tree_df %>%
  group_by(boroname) %>%
  dplyr::summarise(total = n()) 
```

```{r warning=F}
ggplot(aes(x = latitude, y = longitude), data = tree_df) +
  geom_hex()
```

```{r warning=F}
zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
  dplyr::select(-zipcode_no, -uhf42_code) %>%
   filter(is.na(zipcode) == FALSE)

tree_total_uhf42 = left_join(tree_df, zipcode_uhf42, by = "zipcode") %>%
  group_by(uhf42_name) %>%
  dplyr::summarize(total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, total))
```

```{r warning=F}
zipcode_uhf42 = read_excel("./data/Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
 dplyr::select(-zipcode_no, -uhf42_code) %>%
   filter(is.na(zipcode) == FALSE)

mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")
area = mydat$SHAPE_Area

tree_total_uhf42 = left_join(tree_df, zipcode_uhf42, by = "zipcode") %>%
  group_by(uhf42_name) %>%
  dplyr::summarize(total = n()) %>%
  mutate(area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  mutate(tree_density = total/area, 
         uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))

ggplot(aes(x = uhf42_name, y = tree_density), data = tree_total_uhf42) +
  geom_bar(stat = "identity", aes(fill = uhf42_name)) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1)) +
  theme(legend.position = "none")
```

```{r warning=F}
asthma_pollute = read_csv("./data/asthma_air/Data.csv")

pm2.5 = asthma_pollute %>%
  filter(name == "Fine Particulate Matter (PM2.5)", Measure == "Mean", year_description == "Annual Average 2015") %>%
  dplyr::rename(uhf42_name = geo_entity_name) %>%
 dplyr::select(uhf42_name, pm2.5_data = data_value)

pm2.5_tree = left_join(pm2.5, tree_total_uhf42)

summary(lm(pm2.5_data ~ tree_density, data = pm2.5_tree))

ggplot(aes(x = tree_density, y = pm2.5_data), data = pm2.5_tree) +
  geom_point()+
  geom_smooth()

asthma_hos_children = asthma_pollute %>%
  filter(name == "Asthma Hospitalizations (Children 0 to 4 Yrs Old)", Measure == "Rate", year_description == "2015") %>%
  dplyr::rename(uhf42_name = geo_entity_name) %>%
 dplyr::select(uhf42_name, asthma_hos_children = data_value)

asthma_hos_children_tree = left_join(asthma_hos_children, tree_total_uhf42)

summary(lm(asthma_hos_children ~ tree_density, data = asthma_hos_children_tree))

ggplot(aes(x = tree_density, y = asthma_hos_children), data = asthma_hos_children_tree) +
  geom_point()+
  geom_smooth()
```

```{r warning=F}
asthma_pm = left_join(pm2.5, asthma_hos_children)

summary(lm(asthma_hos_children ~ tree_density, data = asthma_hos_children_tree))

ggplot(aes(x = tree_density, y = asthma_hos_children), data = asthma_hos_children_tree) +
  geom_point()+
  geom_smooth()
```
