---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: spacelab
---

```{r debug, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readxl)
library(rgdal)
library(leaflet)
<<<<<<< HEAD
library(rvest)
library(httr)
###
tree_df = GET("https://data.cityofnewyork.us/api/views/5rq2-4hqu/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")

=======
library(httr)

## Tidy tree data
tree_df = GET("https://data.cityofnewyork.us/api/views/5rq2-4hqu/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")

>>>>>>> 6649264d36b56d14a2b43e874f90ad9f4a575abf
tree_df = tree_df %>%
  janitor::clean_names() %>%
  filter(status == "Alive") %>%
  select(zipcode, latitude, longitude)
<<<<<<< HEAD

download.file("https://raw.githubusercontent.com/BS1125/project_data/master/Zipcode_UHF42.xlsx",mode = "wb",destfile = "Zipcode_UHF42.xlsx")

=======

download.file("https://raw.githubusercontent.com/BS1125/project_data/master/Zipcode_UHF42.xlsx",mode = "wb",destfile = "Zipcode_UHF42.xlsx")

>>>>>>> 6649264d36b56d14a2b43e874f90ad9f4a575abf
zipcode_uhf42 = read_excel("Zipcode_UHF42.xlsx") %>%
   gather(key = zipcode_no, value = zipcode, zipcode1:zipcode9) %>%
   select(-zipcode_no, uhf42_name) %>%
   filter(is.na(zipcode) == FALSE)

tree_df = left_join(tree_df, zipcode_uhf42, by = "zipcode") 

download.file("https://catharob.carto.com/api/v2/sql?filename=uhf_42_dohmh_2009&q=SELECT+*+FROM+(select+*+from+public.uhf_42_dohmh_2009)+as+subq+&format=csv&bounds=&api_key=&skipfields=the_geom_webmercator",destfile = "UHF_42.csv")

area = read_csv("UHF_42.csv") %>%
  filter(uhfcode != 0) %>%
  select(uhf42_code = uhfcode, area = shape_area)

tree_df = left_join(tree_df, area, by = "uhf42_code")

<<<<<<< HEAD
#read and tidy data
download.file("https://raw.githubusercontent.com/BS1125/project_data/master/asthma_pollutes_poverty.csv",mode = "wb",destfile = "asthma_air_poverty.csv")

asthma_air_poverty = read_csv("asthma_air_poverty.csv") %>%
  select(geo_entity_id, geo_entity_name, name, data_value) %>%
  filter(is.na(geo_entity_id) == FALSE) %>%
  spread(key = name, value = data_value) %>%
  janitor::clean_names() %>%
  select(poverty, children_under_5_years_old_in_poverty, everything()) %>%
  mutate(asthma_total = asthma_emergency_department_visits_children_0_to_4_yrs_old + asthma_emergency_department_visits_children_5_to_14_yrs_old,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total))
=======
## Tidy map data
mydat = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")
area=data.frame(uhf42_code = mydat$UHFCODE,area = mydat$SHAPE_Area) %>%
  filter(is.na(uhf42_code) == FALSE)
>>>>>>> 6649264d36b56d14a2b43e874f90ad9f4a575abf

tree_density = tree_df %>%
  group_by(uhf42_name, uhf42_code, area) %>%
  dplyr::summarize(tree_total = n()) %>%
  filter(is.na(uhf42_name) == FALSE) %>%
  group_by(uhf42_name) %>%
  dplyr::mutate(tree_density = tree_total/area) %>%
  ungroup() %>%
  mutate(uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))

<<<<<<< HEAD
=======
## Tidy map data
map_data = fortify(mydat) %>%
  dplyr::select(id, everything() )%>%
  nest(long:group)
map_data$uhf = mydat$UHFCODE
map_data = map_data %>%
  unnest %>%
  dplyr::select(-id) %>%
  dplyr::select(id = uhf, everything()) %>%
  dplyr::select(long, lat, everything())
names(map_data)[1:2] = c("x","y") 

## Tidy asthma data
asthma_air_poverty = read_csv("./data/asthma_pollutes_poverty.csv") %>%
  select(geo_entity_id, geo_entity_name, name, data_value) %>%
  filter(is.na(geo_entity_id) == FALSE) %>%
  spread(key = name, value = data_value) %>%
  janitor::clean_names() %>%
  select(poverty, children_under_5_years_old_in_poverty, everything()) %>%
  mutate(asthma_total = asthma_emergency_department_visits_children_0_to_4_yrs_old + asthma_emergency_department_visits_children_5_to_14_yrs_old,
         geo_entity_name = forcats::fct_reorder(geo_entity_name, asthma_total))

## Join all together
>>>>>>> 6649264d36b56d14a2b43e874f90ad9f4a575abf
tree_density_total = tree_density %>%
  select(geo_entity_id=uhf42_code, tree_density) %>%
  distinct()

final_df = left_join(asthma_air_poverty, tree_density_total)


## Asthma_map

asthma_map = final_df %>%
  dplyr::select (id = geo_entity_id, asthma = asthma_total,geo_entity_name) 
names(final_df)
final_asthma_df = gather(final_df, key = asthma_age, value = rate, asthma_emergency_department_visits_children_0_to_4_yrs_old:asthma_emergency_department_visits_children_5_to_14_yrs_old) %>%
  gather(key = poverty_age, value = poverty, poverty:children_under_5_years_old_in_poverty) %>%
  filter((asthma_age == "asthma_emergency_department_visits_children_5_to_14_yrs_old"&poverty_age == "poverty")|(asthma_age == "asthma_emergency_department_visits_children_0_to_4_yrs_old"& poverty_age == "children_under_5_years_old_in_poverty"))
```

```{r }
#tree density


### MAP

mydat2 = rgdal::readOGR("./UHF42/UHF_42_DOHMH.shp")

mydat2$UHFCODE
proj4string1 =  "+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80
+towgs84=0,0,0" 
mydat2 = spTransform(mydat2, proj4string1)
proj4string(mydat2)


theme_set(theme_bw())
```


Column {data-width=450}
---------------------------------------------------------------------

### Tree distribution in New York City

```{r debug2}

<<<<<<< HEAD

=======
>>>>>>> 6649264d36b56d14a2b43e874f90ad9f4a575abf
tree_total_uhf42 = tree_df %>%
  group_by(uhf42_name, area,uhf42_code) %>%
  dplyr::summarize(total = n()) %>%
  mutate(spc_common = "Total") %>%
  filter(is.na(uhf42_name) == FALSE) %>%
   group_by(spc_common) %>%
  mutate(tree_density = total/area, 
<<<<<<< HEAD
         uhf42_name = forcats::fct_reorder(uhf42_name, tree_density)) 

=======
         uhf42_name = forcats::fct_reorder(uhf42_name, tree_density))
>>>>>>> 6649264d36b56d14a2b43e874f90ad9f4a575abf

total_tree = tree_total_uhf42 %>%
  ungroup() %>%
  dplyr::select(UHFCODE= uhf42_code, everything()) %>%
  arrange(UHFCODE) %>%
  mutate(tree_density = tree_density*100000)

pal <- colorBin("Greens", total_tree$tree_density, 5, pretty = FALSE)

leaflet() %>% 
addProviderTiles("OpenStreetMap.Mapnik") %>%
setView(lat = 40.7, lng = -74, zoom = 11) %>%
addPolygons(data = mydat2, fillColor = ~pal(total_tree$tree_density), weight = 1,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.65, 
  popup = paste("Region: ", total_tree$uhf42_name, "<br>",
                          "Number: ", total_tree$total, "<br>")) %>%
  addLegend(position = "bottomright", pal = pal, values =total_tree$tree_density,
          title = "Tree density(E-6)",
          opacity = 1, bins = F)

```


Column {data-width=350}
-----------------------------------------------------------------------

### Asthma and Tree

```{r}

bfigure =  ggplot(final_asthma_df) +
  geom_point(aes(x = tree_density, y = rate, color = asthma_age)) +
   geom_smooth(aes(x = tree_density, y = rate, color = asthma_age), method = "lm",se = F) +
   labs(
    title = "Asthma and Tree Density",
    x = "Tree Density",
    y = "Asthma Rate"
  ) +
   theme(legend.position='none') +
   guides(color = guide_legend(nrow = 2)) +
   scale_color_hue(name = "Age")

ggplotly(bfigure)





```

### Tree Density and Sulfur Dioxide

```{r}

cfigure = ggplot(final_asthma_df) +
  geom_point(aes_string(x ="sulfur_dioxide_so2", y = "tree_density")) +
  geom_smooth(aes_string(x = "sulfur_dioxide_so2", y = "tree_density"), method = "lm", se = F, color = "#2c7fb8") +
   labs(
    x = "Sulfur dioxide",
    y = "Tree Density"
  ) 

ggplotly(cfigure)
```